### PR TITLE
added initial flake8 tox and travis configuration

### PR DESCRIPTION
**Pull request by peterlauri**
Initial flake8 configuration. Took it out from django flake8 configuration, with exception of the exclude.

If this is something that is wanted, then I will do the code changes based on flake8 errors, and then you can consider it for merging.

### CODE REVIEW

**Comment by spookylukey** [comment]
I think we should probably:
* enable W503
* enable W603
* enable E402 and just override with '# noqa' comments when needed.

With that, please go ahead with the flake8 changes - thanks!

Also, for both flake8/isort I think it would help to exclude the 'dist' and 'build' directories (which happen at least when you create packages).

**Comment by peterlauri** [comment]
W603 is already enabled, do you maybe refer to W601? I make the assumption about that, it makes sense to warn about that...

**Comment by spookylukey** [comment]
Yep, I meant W601. Thanks so much for this!

**Comment by peterlauri** [comment]
NP!

**Pull request merged**
