### PR TITLE
Simplified payment button customisation. #196

### PR DESCRIPTION
**Pull request by fabiocaccamo**

### CODE REVIEW

**Comment by fabiocaccamo** [comment]
With this PR it is possible to customise the payment button by doing just this:

```python
from django.utils.html import format_html

from paypal.standard.forms import PayPalPaymentsForm


class CustomPayPalPaymentsForm(PayPalPaymentsForm):

    def get_html_submit_element(self):
        return format_html(
            """<button type="submit">Continue on PayPal website</button>"""
        )
```

**Comment by spookylukey** [comment]
This looks like a nice improvement, thanks!

Would you be able to write some docs? I think a new section on overriding the form at the bottom of this page would be good: https://django-paypal.readthedocs.io/en/latest/standard/ipn.html

**Comment by fabiocaccamo** [comment]
@spookylukey I updated the docs adding the button customisation block and fixing a broken link.

**Comment by spookylukey** [comment]
Thanks!

**Pull request merged**
