### PR TITLE
isort addition to travis/tox testenv

### PR DESCRIPTION
**Pull request by peterlauri**
Related to #122 request, but only with the tox.ini and .travis.yml changes for isort checks.

### CODE REVIEW

**Comment by peterlauri** [comment]
So now the travis job fails, of course :) Look at the travis job, and you will see that the import checks are failing. If this is ok, then I will go ahead and run isort and commit it, so the configuration in setup.cfg can be fine tuned.

**Comment by spookylukey** [comment]
Looks great, please go ahead as proposed.

**Comment by peterlauri** [comment]
Also, the configured line length is 120, as per django style guide. Actually, maybe it should be 119 :/

https://docs.djangoproject.com/en/1.9/internals/contributing/writing-code/coding-style/

But maybe we should just use djangos isort configuration then, with exception of the known_first_party and line length (that they enforce via flake8).

```
[isort]
combine_as_imports = true
default_section = THIRDPARTY
include_trailing_comma = true
known_first_party = django
multi_line_output = 5
not_skip = __init__.py
```

**Comment by spookylukey** [comment]
Thanks so much for this, that's excellent!

**Comment by peterlauri** [comment]
You are welcome! :)

**Pull request merged**
