### PR TITLE
Fix encrypted buttons under Python 3

### PR DESCRIPTION
**Pull request by JonathanRoach**
Avoid the b'' decoration under Python 3 when mixing binary (encrypted button contents) and normal strings. Fix the examples in the documentation for encrypted buttons to use the encrypted form.

### CODE REVIEW

**Comment by spookylukey** [comment]
Thanks so much for the PR! This code needs tests (tests that fail without the patch) in order to be merged.

**Comment by JonathanRoach** [comment]
Hi Luke,

Sorry, I’m not ignoring you - I’m just prioritising finishing some other things off first.

Jon

**Comment by spookylukey** [comment]
BTW, there is no need to bump version numbers, I'll do that when I release.

**Comment by JonathanRoach** [comment]
Test written (bug fixed - oops), doc updated (M2Crypto is now Python3 capable), and .DS_Store added to .gitignore (for Mac users).

**Comment by spookylukey** [comment]
Would you be able to fix the merge conflicts? It looks the main problem is the version number bumps - just drop all your changes in that regard, and put docs the "under development" heading. Thanks!

**Comment by mmic** [comment]
I attest the issue. PayPal checkouts would have stopped working after migrating our codebase to python 3. How can we contribute tests to have this patch merged?

**Comment by JonathanRoach** [comment]
I think I've adjusted the notes & versioning to merge correctly now.

**Comment by mmic** [comment]
Careful, the original patch is incorrect. ".decode()" should be appended, not ".encode()".

**Comment by JonathanRoach** [comment]
The revision 'Add test for encrypted buttons' includes the correction to .decode() - tests are a good thing!

**Comment by JonathanRoach** [comment]
The automated tests aren’t working - m2crypto needs installing. Is the correct fix to add:
- install m2crypto>=0.29
just before:
- install tox>=2.1
in travis.yml?

**Comment by spookylukey** [comment]
@JonathanRoach - you should instead modify tox.ini to add the dependency under the `deps =` section. You can test locally by doing something like:

    $ pip install tox
    $ tox -e py27-django111-tests-usetztrue -e py35-django200-tests-usetztrue

(i.e. one Python 2 and one Python 3 environment).

I normally use exact versions in tox.ini (e.g. m2crypto==0.29 rather than m2crypto>=0.29), so that we don't get unexpected failures on Travis caused by some new incompatibility in a recent version of something.

**Comment by spookylukey** [comment]
Looks good - thanks so much!

**Pull request merged**
