### PR TITLE
Change input format from all DateTimeFields.

### PR DESCRIPTION
**Pull request by thiagogds**
Some fields were not covered yet.
Issue #26

### CODE REVIEW

**Comment by spookylukey** [comment]
Thanks so much for this. The patch has just been outdated by more recent changes (I now have PayPalDateTimeField which encapsulates this and other logic). Any chance you could update your patch?

**Comment by thiagogds** [comment]
Sure. I will update it

**Comment by thiagogds** [comment]
I merged the new commits into my branch.

**Comment by spookylukey** [comment]
Thanks so much, this is merged now, and in release 0.2.5

**Pull request merged**
